"""
process_pointcloud.py

This script is designed to process raw scan data generated by `PointcloudMapper.py`.
It reads a CSV file containing rotational angles and corresponding vertical depth
slices captured from a Kinect V2 sensor. The raw 2D depth slices are then converted
into a 3D point cloud in a global coordinate system.

The resulting 3D point cloud is saved as a `.pcd` (Point Cloud Data) file,
which can be visualized and further processed using tools like Open3D.

Key Features:
- Automatically identifies the latest `raw_scan_data_*.csv` file for processing.
- Utilizes Kinect V2 intrinsic camera parameters to convert 2D depth pixels into 3D coordinates.
- Transforms sensor-relative 3D points into world-relative coordinates based on the
  rotational angle recorded during the scan.
- Filters out invalid depth readings and points beyond a specified scan range.
- Reduces point cloud density by processing a subset of vertical pixels.
- Saves the final 3D point cloud to a `.pcd` file using the Open3D library.

Dependencies:
- csv: For reading the raw data from CSV files.
- numpy: For numerical operations and array manipulation.
- glob, os: For file system operations (finding files, path manipulation).
- math: For trigonometric calculations.
- open3d: For creating and saving `.pcd` files.
"""

import csv
import numpy as np
import glob
import os
import math
import open3d as o3d

# --- Configuration ---
OUTPUT_PCD_FILENAME = "point_cloud_3d.pcd" # Name of the output Point Cloud Data file.
SCAN_RANGE_METERS = 8.0                    # Maximum depth distance (in meters) to consider for points.
VERTICAL_PIXEL_STEP = 10                   # Process every Nth vertical pixel to manage point cloud density.

# --- Kinect V2 Depth Camera Intrinsics ---
# These are typical intrinsic parameters for the Kinect V2 depth sensor.
# They are crucial for accurately projecting 2D depth pixels into 3D space.
# (Image width is 512, height is 424 for depth frames).
FX_DEPTH = 365.481 # Focal length in X-direction.
FY_DEPTH = 365.481 # Focal length in Y-direction.
CX_DEPTH = 257.346 # Principal point X-coordinate (horizontal center).
CY_DEPTH = 210.347 # Principal point Y-coordinate (vertical center).

# --- Path Configuration ---
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__)) # Directory where this script resides.
# Raw CSV files are expected to be in the parent 'pi-code' directory.
RAW_DATA_DIR = os.path.join(SCRIPT_DIR, "..") 

def find_latest_raw_scan_file(directory: str) -> str | None:
    """
    Searches the specified directory for the most recently created `raw_scan_data_*.csv` file.

    Args:
        directory (str): The path to the directory to search in.

    Returns:
        str | None: The full path to the latest CSV file, or None if no such file is found.
    """
    search_pattern = os.path.join(directory, 'raw_scan_data_*.csv')
    files = glob.glob(search_pattern)
    if not files:
        return None
    return max(files, key=os.path.getctime) # Return the file with the latest creation time.

def save_points_to_pcd(points: list[list[float]], filename: str):
    """
    Saves a list of 3D points to a `.pcd` (Point Cloud Data) file.

    Args:
        points (list[list[float]]): A list of 3D points, where each inner list
                                    is [x, y, z] in meters.
        filename (str): The name of the `.pcd` file to save the points to.
    """
    if not points:
        print("No points to save.")
        return
    print(f"\nSaving {len(points)} points to '{filename}'...")
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(np.asarray(points)) # Convert list to NumPy array for Open3D.
    o3d.io.write_point_cloud(filename, pcd) # Write the point cloud to file.
    print("✅ Point cloud successfully saved.")

def process_raw_data(filename: str) -> list[list[float]]:
    """
    Reads the raw scan data from the specified CSV file, converts each depth
    pixel from the vertical slices into a 3D point, and transforms these points
    into a global coordinate system based on the recorded rotational angle.

    Args:
        filename (str): The path to the raw scan data CSV file.

    Returns:
        list[list[float]]: A list of 3D points, where each inner list is
                           [world_x, world_y, world_z] in meters. Returns an
                           empty list if processing fails or no valid data is found.
    """
    print(f"Reading raw data from '{filename}'...")
    world_points = []
    
    try:
        with open(filename, 'r') as f:
            csv_reader = csv.reader(f)
            for i, row in enumerate(csv_reader):
                if not row: continue # Skip empty rows.
                
                current_angle_deg = float(row[0]) # First element is the rotational angle in degrees.
                current_angle_rad = math.radians(current_angle_deg) # Convert to radians for trigonometric functions.
                depth_slice_str = row[1:] # Remaining elements are depth values as strings.
                
                # Process the vertical slice of depth data.
                # Iterate with VERTICAL_PIXEL_STEP to reduce density.
                for v_raw, depth_str in enumerate(depth_slice_str[::VERTICAL_PIXEL_STEP]):
                    depth_mm = float(depth_str)
                    
                    # Filter out invalid depth readings (0) or points beyond the scan range.
                    if depth_mm == 0 or depth_mm > (SCAN_RANGE_METERS * 1000):
                        continue

                    v = v_raw * VERTICAL_PIXEL_STEP # Calculate the actual vertical pixel index.
                    center_u = 256 # The slice was taken from the horizontal center of the sensor (512 / 2).

                    # Convert depth from millimeters to camera-space coordinates (in meters).
                    z_cam = depth_mm / 1000.0 # Convert depth to meters.
                    x_cam = (center_u - CX_DEPTH) * z_cam / FX_DEPTH
                    y_cam = (v - CY_DEPTH) * z_cam / FY_DEPTH

                    # Rotate the camera-space point into world-space using the current rotational angle.
                    # The rotation is around the vertical (Y) axis.
                    world_x = z_cam * math.sin(current_angle_rad) + x_cam * math.cos(current_angle_rad)
                    world_y = y_cam # Height (Y) is not affected by rotation around the vertical axis.
                    world_z = z_cam * math.cos(current_angle_rad) - x_cam * math.sin(current_angle_rad)
                    
                    world_points.append([world_x, world_y, world_z])
                
                print(f"Processing line {i+1}...", end='\r')

    except FileNotFoundError:
        print(f"Error: File not found at '{filename}'")
        return []
    except Exception as e:
        print(f"\nAn error occurred during processing: {e}")
        return []

    return world_points

if __name__ == "__main__":
    """
    Main execution block for the point cloud processing script.

    When run directly, it finds the latest raw scan data CSV file, processes it
    into a 3D point cloud, and saves the result as a `.pcd` file.
    It provides instructions if no raw data file is found.
    """
    print("--- Raw Scan Data Processor ---")
    latest_csv = find_latest_raw_scan_file(RAW_DATA_DIR)
    
    if latest_csv:
        collected_points_3d = process_raw_data(latest_csv)
        
        if collected_points_3d:
            # Save the generated point cloud to the script's directory.
            output_path = os.path.join(SCRIPT_DIR, OUTPUT_PCD_FILENAME)
            save_points_to_pcd(collected_points_3d, output_path)
    else:
        print(f"No raw_scan_data_*.csv file found in '{RAW_DATA_DIR}'.")
        print("Please run 'PointcloudMapper.py' first to generate data.")
