"""
view_map.py

This script is designed to load and visually display a 3D point cloud from a
`.pcd` (Point Cloud Data) file. It utilizes Matplotlib for visualization,
making it suitable for environments that may not have a full graphical desktop
environment, such as a Raspberry Pi.

The script expects a `point_cloud_3d.pcd` file, typically generated by
`process_pointcloud.py`, and renders it as a 3D scatter plot. It includes
functionality to sub-sample large point clouds to prevent performance issues
during visualization.

Dependencies:
- open3d: For reading and handling `.pcd` files.
- os: For path manipulation and file existence checks.
- numpy: For numerical operations and array manipulation.
- matplotlib.pyplot: For creating and displaying 2D/3D plots.
- mpl_toolkits.mplot3d: Specifically for 3D plotting capabilities in Matplotlib.
"""

import open3d as o3d
import os
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# --- Path Configuration ---
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__)) # Directory where this script resides.
PCD_FILENAME = os.path.join(SCRIPT_DIR, "point_cloud_3d.pcd") # Full path to the expected PCD file.
MAX_POINTS_TO_DISPLAY = 30000  # Limits the number of points displayed to prevent performance issues with Matplotlib.

def view_pcd_with_matplotlib(filename: str):
    """
    Loads a 3D PCD file from the specified filename and displays it using
    a Matplotlib 3D scatter plot.

    The function checks for file existence, loads the point cloud, optionally
    sub-samples it if too large, and then configures and displays a 3D plot.
    Points are colored by their height (Y-coordinate) for better depth perception.

    Args:
        filename (str): The full path to the `.pcd` file to be loaded and displayed.
    """
    if not os.path.exists(filename):
        print(f"Error: PCD file not found at '{filename}'")
        print("Please run 'process_pointcloud.py' first to generate the 3D PCD file.")
        return

    try:
        print(f"Loading point cloud from '{filename}'...")
        pcd = o3d.io.read_point_cloud(filename)
        if not pcd.has_points():
            print("Error: The PCD file is empty or contains no points.")
            return

        points = np.asarray(pcd.points) # Convert Open3D points to a NumPy array.
        print(f"Loaded {len(points)} points.")

        # Sub-sample points if the cloud is too large for efficient Matplotlib rendering.
        if len(points) > MAX_POINTS_TO_DISPLAY:
            print(f"Sub-sampling to {MAX_POINTS_TO_DISPLAY} points for display...")
            # Randomly select a subset of points without replacement.
            indices = np.random.choice(points.shape[0], MAX_POINTS_TO_DISPLAY, replace=False)
            points_to_display = points[indices]
        else:
            points_to_display = points

        print("Preparing 3D plot...")
        fig = plt.figure(figsize=(12, 12)) # Create a new figure for the plot.
        ax = fig.add_subplot(111, projection='3d') # Add a 3D subplot.

        # Extract X, Y, Z coordinates from the points.
        x = points_to_display[:, 0]
        y = points_to_display[:, 1] # Y-coordinate typically represents height.
        z = points_to_display[:, 2]

        # Create a 3D scatter plot.
        # Points are colored based on their Y-coordinate (height) using a 'viridis_r' colormap.
        # We plot (x, z, y) to achieve a more natural top-down perspective, where Z is forward/backward.
        ax.scatter(x, z, y, s=1, c=y, cmap='viridis_r')

        # Set axis labels and plot title.
        ax.set_xlabel("X (meters)")
        ax.set_ylabel("Z (meters)")
        ax.set_zlabel("Y / Height (meters)")
        ax.set_title("3D Point Cloud Map")
        
        # Set the aspect ratio to be equal for a geometrically accurate representation.
        # This prevents distortion of the 3D space.
        max_range = np.array([x.max()-x.min(), y.max()-y.min(), z.max()-z.min()]).max()
        mid_x = (x.max()+x.min()) * 0.5
        mid_y = (y.max()+y.min()) * 0.5
        mid_z = (z.max()+z.min()) * 0.5
        ax.set_xlim(mid_x - max_range * 0.5, mid_x + max_range * 0.5)
        ax.set_ylim(mid_z - max_range * 0.5, mid_z + max_range * 0.5)
        ax.set_zlim(mid_y - max_range * 0.5, mid_y + max_range * 0.5)

        print("Displaying plot. Close the plot window to exit.")
        plt.show() # Display the plot. This call is blocking until the window is closed.

    except Exception as e:
        print(f"An error occurred while trying to display the PCD file: {e}")

if __name__ == "__main__":
    """
    Entry point for the script when executed directly.

    It calls the `view_pcd_with_matplotlib` function with the predefined
    PCD filename.
    """
    view_pcd_with_matplotlib(PCD_FILENAME)
